---
title: "UCI HAR Codebook"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
    code_folding: hide
    self_contained: yes
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = FALSE  # show R code
)

```


```{r prepare_codebook}
#install.packages("codebook")
#install.packages("rio")
#install.packages("future")
library(rio)
library(codebook)
library(future)
codebook_data<- rio::import("./Week 1/final_tidy.csv") #-imports CSV data
```

# UCI HAR Dataset Run-Analysis Codebook
```{r create_codebook}
codebook(codebook_data)
```


# UCI HAR Dataset Codebook

## Background 
```{r background_codebook}
#install.packages("readr")
library(readr)
url1<-
  "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
temp <-tempfile()
download.file(url1,temp, mode="w")
Background<-readLines(unzip(temp, "UCI HAR Dataset/README.txt"))
Background
```

## Features & Activity Labels Information
```{r Features & Activity}

Features<-read.table(unzip(temp, "UCI HAR Dataset/features.txt"), sep="")
Activity_labels<-read.table(unzip(temp, "UCI HAR Dataset/activity_labels.txt"), sep="")
Features
Activity_labels


```
